---
- hosts: all
  # gather_facts: no

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
      become: yes


  tasks:

    - name: Pull Redmine Docker image
      docker_image:
        name: redmine:latest
        source: pull
      tags: pull
