---
- hosts: all
  # gather_facts: no


  become: yes
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker


  tasks:

    - name: Pull Redmine Docker image
      docker_image:
        name: redmine:latest
        source: pull
      tags: prepare

    - name: Create .env file from template
      template:
        src: "{{ local_project_path }}/templates/env.j2"
        dest: "{{ server_env_path }}"
      tags: deploy

    - name: Run Redmine container
      docker_container:
        name: redmine
        image: redmine
        state: started
        env_file: "{{ server_env_path }}"
        network_mode: host
      tags: deploy



- hosts: webservers
  become: yes
  roles:
    - datadog.datadog
  tasks:
    - name: Configure HTTP check for DataDog
      template: 
        src: "{{ local_project_path }}/templates/datadog/http_check.yaml.j2"
        dest: /etc/datadog-agent/conf.d/http_check.d/conf.yaml
      notify:
        - Restart DataDog Agent
      tags: datadog

  handlers:
    - name: Restart DataDog Agent
      systemd:
        state: restarted
        name: datadog-agent